version: "2"

services:
  rabbit:
    image: rabbitmq:3-management
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
      
  calculator:
      build: ./calculator
      links:
        - rabbit
      depends_on:
        - rabbit
      command: dotnet run
    
  initializer:
      build: ./initializer
      links:
        - rabbit
      depends_on:
        - rabbit
      command: dotnet run

  pdfgen:
      build: ./pdfgen
      links:
        - rabbit
      depends_on:
        - rabbit
      command: dotnet run

  web:
      build: ./web
      ports:
        - "5000:5000"
      links:
        - rabbit
      depends_on:
        - rabbit
      env_file: .env
      volumes:
        - ./web:/code
      depends_on:
        - rabbit
      command: dotnet run --server.urls=http://0.0.0.0:5000
